# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9177762e7f78ebf7bab160e472ec2544990619cae8969c7b865de2b120ad7ac204bfd6415d3546d6e0c9585baf1a65861747a972cbec4e0a73a3688b0a5b135a

test:
  secret_key_base: 47cfde8b7ba2969f9e3627d2be8e91ca450e49f658fa9c6c6e516e7716c5c001ef6fd4f6dd06fd9310ba3dcf666d9f9266e4d006ab7aac923c4c7f4ede0a20ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
